apiVersion: apps/v1
kind: ReplicaSet #Tipo de objeto de Kubernetes
metadata:
  name: es-cliente-rs #Nombre del ReplicaSet
  labels: #Etiquetas que permiten relacionar objetos
    app: cliente
    tier: back-end
spec:
  replicas: 3 #La cantidad de réplicas(instancias) del servicio
  selector: #Define la relación con el POD que se debe monitorear
    matchLabels:
      app: es-cliente
  template: #Define el contenedor que se debe instanciar
    metadata:
      labels:
        app: es-cliente
    spec:
      containers:
        - name: es-cliente
          image: jorgeheredia/microservices-lab:es-cliente-v1.0.0
        - name: mongo-cliente
          image: mongo:4.0.14
      imagePullSecrets:
        - name: dockerhubkey #Nombre del Secret creado para autenticarse a DockerHub

