#Variables referentes a kubernetes
kubernetes:
  api:
  #imagen que sera utilizada en el despliegue
    image:
      repository: jorgeheredia/microservices-lab
      tag: "ms-consultarinscripciones"
      version: "-v1.0.0"
    #cantidad de replicas a utilizar
    replicaCount: 1
    service:
      type: LoadBalancer
      port: 1009
    container:
      port: 1009
    ingress:
    #url desde la cual sera accedida el api
      host: ms.consultarinscripcion
    #nombre global del aplicativo
    nombre_global: ms-consultarins
  db:
    image:
      repository: mongo
      tag: "4.0.14"
    service:
      type: LoadBalancer
      port: 27017
    container:
      port: 27017
    #nombre global del aplicativo
    nombre_global: db-consulinscri
    database_name: inscripcionesReplicaDB
    collection_name: Agenda
    
global:
  namespace: default
