kubernetes:
  api:
    image:
      repository: jorgeheredia/microservices-lab
      tag: "ms-consultarinscripciones"
      version: "-v1.0.0"
    replicaCount: 1
    service:
      type: NodePort
      port: 1009
    container:
      port: 1009
    ingress:
      host: ms.consultarinscripcion
    nombre_global: ms-consultarins
  db:
    image:
      repository: mongo
      tag: "4.0.14"
    service:
      type: NodePort
      port: 27017
    container:
      port: 27017
    nombre_global: db-consulinscri
    database_name: inscripcionesReplicaDB
    collection_name: Inscripciones
    
global:
  namespace: default
