Vagrant.configure("2") do |config|

    config.vm.box = "itehl-microlab"

    config.ssh.password = 'vagrant'
    config.ssh.insert_key = false
#Puertos APIs
    
    config.vm.network "forwarded_port", guest: 1001, host: 1001
    config.vm.network "forwarded_port", guest: 1002, host: 1002
    config.vm.network "forwarded_port", guest: 1003, host: 1003
    config.vm.network "forwarded_port", guest: 1004, host: 1004
    config.vm.network "forwarded_port", guest: 1005, host: 1005
    config.vm.network "forwarded_port", guest: 1006, host: 1006
    config.vm.network "forwarded_port", guest: 1007, host: 1007
    config.vm.network "forwarded_port", guest: 1008, host: 1008
    config.vm.network "forwarded_port", guest: 1009, host: 1009

#Puertos DB

    config.vm.network "forwarded_port", guest: 27018, host: 27018
    config.vm.network "forwarded_port", guest: 27019, host: 27019
    config.vm.network "forwarded_port", guest: 27020, host: 27020
    config.vm.network "forwarded_port", guest: 27021, host: 27021
    config.vm.network "forwarded_port", guest: 27022, host: 27022
    config.vm.network "forwarded_port", guest: 27023, host: 27023

#Puertos Infra

    config.vm.network "forwarded_port", guest: 8500, host: 8500
    
    config.vm.define "Itehl_MicroservicesLab" do |node| 
      node.vm.hostname = "MicroservicesLab"  
      node.vm.provider "virtualbox" do |vb|
        # Habilita la conexion a internet
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.memory = 4000
        vb.cpus = 2
        vb.name = "Itehl_MicroservicesLab"

  
      end
      node.vm.provision :shell, inline: <<-SHELL
      git clone https://itehllabs:L4bs1th3l2020*.@github.com/repo-itehl/microservices-lab.git
      SHELL
   end
  
  end
