Vagrant.configure("2") do |config|

    config.vm.box = "itehl-digital/itehl-microlab"
    config.ssh.insert_key = false
    # Habilita la conexion a internet
    config.vm.define "node" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            vb.gui = false
            vb.name = "Itehl_MicroLab"
            vb.memory = 4000
            vb.cpus = 3
        end
        node.vm.provision :shell, inline: <<-SHELL
          echo 'export PATH=$PATH:/snap/bin' >> ~/.bashrc
          git clone https://itehllabs:L4bs1th3l2020*.@github.com/repo-itehl/microservices-lab.git
          docker-compose -f /home/vagrant/microservices-lab/Compose/docker-compose-infra.yml up -d
        SHELL
    end
#Puertos APIs
    
    config.vm.network "forwarded_port", guest: 1001, host: 1001
    config.vm.network "forwarded_port", guest: 1002, host: 1002
    config.vm.network "forwarded_port", guest: 1003, host: 1003
    config.vm.network "forwarded_port", guest: 1004, host: 1004
    config.vm.network "forwarded_port", guest: 1005, host: 1005
    config.vm.network "forwarded_port", guest: 1006, host: 1006
    config.vm.network "forwarded_port", guest: 1007, host: 1007
    config.vm.network "forwarded_port", guest: 1008, host: 1008
    config.vm.network "forwarded_port", guest: 1009, host: 1009

#Puertos DB

    config.vm.network "forwarded_port", guest: 27017, host: 27017

#Puertos Infra

    config.vm.network "forwarded_port", guest: 8500, host: 8500

    end
  

