Vagrant.configure("2") do |config|

    config.vm.box = "itehl-digital/itehl-microlab"
    config.ssh.password = 'vagrant'
    config.ssh.insert_key = false
    # Habilita la conexion a internet
    config.vm.define "node" do |node|
        node.vm.boot_timeout = 600
        node.vm.provider "virtualbox" do |vb|
            vb.gui = true
            vb.name = "Itehl_MicroLab"
            vb.memory = 8000
            vb.cpus = 4
        end

        node.vm.network "public_network", ip:"186.165.25.25",  bridge: "Intel(R) Dual Band Wireless-AC 3165"
        node.vm.provision :shell, inline: <<-SHELL
          sudo snap install helm --classic
          git clone https://itehllabs:L4bs1th3l2020*.@github.com/repo-itehl/microservices-lab.git
          #docker-compose -f /home/vagrant/microservices-lab/Compose/docker-compose-infra.yaml up -d
        SHELL
    end
#Puertos APIs
    
    config.vm.network "forwarded_port", guest: 1001, host: 1001
    config.vm.network "forwarded_port", guest: 1002, host: 1002
    config.vm.network "forwarded_port", guest: 1003, host: 1003
    config.vm.network "forwarded_port", guest: 1004, host: 1004
    config.vm.network "forwarded_port", guest: 1005, host: 1005
    config.vm.network "forwarded_port", guest: 1006, host: 1006
    config.vm.network "forwarded_port", guest: 1007, host: 1007
    config.vm.network "forwarded_port", guest: 1008, host: 1008
    config.vm.network "forwarded_port", guest: 1009, host: 1009
    config.vm.network "forwarded_port", guest: 80, host: 80

#Puertos DB

    config.vm.network "forwarded_port", guest: 27017, host: 27017

#Puertos Infra

    config.vm.network "forwarded_port", guest: 8500, host: 8500

    end
  

