apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kubernetes.api.nombre_global }}-pod #Campo obligatorio para identificar el deployment
  labels:
    version: "v1"
    tier: backend
    service_model: Microservice
    env: dev
    app: {{ .Values.kubernetes.api.nombre_global }}
spec:
  replicas: {{ .Values.kubernetes.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kubernetes.api.nombre_global }}-pod  #nombre base que tendra el pod que tiene que coincidir con el templates.app
  template:
    metadata:
      labels:
        version: "v1"
        app: {{ .Values.kubernetes.api.nombre_global }}-pod
    spec:
      containers:
        - image: {{ .Values.kubernetes.api.image.repository }}:{{.Values.kubernetes.api.image.tag}}{{.Values.kubernetes.api.image.version }} #Se declara la ubicacion del repositorio y la imagen a utilizar
          name: {{ .Values.kubernetes.api.nombre_global }} #nombre base que tendra el contenedor dentro del pod
          ports:
            - containerPort: {{ .Values.kubernetes.api.container.port }}
        - image: {{ .Values.kubernetes.ambassador.image.repository }}:{{.Values.kubernetes.ambassador.image.tag}}{{.Values.kubernetes.ambassador.image.version }} #Se declara la ubicacion del repositorio y la imagen a utilizar
          name: {{ .Values.kubernetes.ambassador.nombre_global }} #nombre base que tendra el contenedor dentro del pod
          ports:
            - containerPort: {{ .Values.kubernetes.ambassador.container.port }}
      imagePullSecrets:
        - name: dockerhubkey
      restartPolicy: Always
