apiVersion: apps/v1
kind: Deployment #Tipo de objeto de Kubernetes
metadata:
  name: {{ .Values.kubernetes.api.nombre_global }}-pod #Nombre del Deployment
  labels: #Etiquetas que permiten relacionar objetos
    version: "v1"
    tier: backend
    service_model: Microservice
    env: dev
    app: {{ .Values.kubernetes.api.nombre_global }}
spec:
  replicas: {{ .Values.kubernetes.api.replicaCount }} #Definición de la cantidad de réplicas del POD
  selector:
    matchLabels:
      app: {{ .Values.kubernetes.api.nombre_global }}-pod #Relación del ReplicaSet con el POD
  template:
    metadata:
      labels:
        version: "v1"
        app: {{ .Values.kubernetes.api.nombre_global }}-pod
    spec:
      containers:
        - image: {{ .Values.kubernetes.api.image.repository }}:{{.Values.kubernetes.api.image.tag}}{{.Values.kubernetes.api.image.version }}
          name: {{ .Values.kubernetes.api.nombre_global }} #Nombre del Contenedor
          ports:
            - containerPort: {{ .Values.kubernetes.api.container.port }}
          imagePullPolicy: Always
        - image: {{ .Values.kubernetes.ambassador.image.repository }}:{{.Values.kubernetes.ambassador.image.tag}}{{.Values.kubernetes.ambassador.image.version }}
          name: {{ .Values.kubernetes.ambassador.nombre_global }} #Nombre del Contenedor
          ports:
            - containerPort: {{ .Values.kubernetes.ambassador.container.port }}
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhubkey  #Nombre del Secret creado para autenticarse a DockerHub
      restartPolicy: Always
