#Variables referentes a kubernetes
kubernetes:
  api:
  #imagen que sera utilizada en el despliegue
    image:
      repository: jorgeheredia/microservices-lab
      tag: "ms-procesarinscripcion"
      version: "-v1.0.0"
    #cantidad de replicas a utilizar
    replicaCount: 1
    service:
      type: ClusterIP
      port: 1001
    container:
      port: 1001
    ingress:
    #url desde la cual sera accedida el api
      host: ms.procesarinscription
    #nombre global del aplicativo
    nombre_global: ms-procesarinscription
  ambassador:
    container:
      port: 1008
    image:
      repository: jorgeheredia/microservices-lab
      tag: "us-correo"
      version: "-v1.0.0"
    nombre_global: us-correo

global:
  namespace: default



