kubernetes:
  api:
    image:
      repository: jorgeheredia/microservices-lab
      tag: "ms-procesarinscripcion"
      version: "-v1.0.0"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 1001
    container:
      port: 1001
    ingress:
      host: ms.procesarinscription
    nombre_global: ms-procesarinscription
  ambassador:
    container:
      port: 1008
    image:
      repository: jorgeheredia/microservices-lab
      tag: "us-correo"
      version: "-v1.0.0"
    nombre_global: us-correo

global:
  namespace: default



