kubernetes:
  api:
    image:
      repository: jorgeheredia/microservices-lab
      tag: "es-inscripcion"
      version: "-v1.0.0"
    replicaCount: 1
    service:
      type: NodePort
      port: 1003
    container:
      port: 1003
    ingress:
      host: es.inscripcion
    nombre_global: es-inscripcion
  db:
    image:
      repository: mongo
      tag: "4.0.14"
    service:
      type: NodePort
      port: 27017
    container:
      port: 27017
    nombre_global: db-incripcion
    database_name: inscripcionesDB
    collection_name: Inscripciones

global:
  namespace: default


