apiVersion: v1
kind: Pod #Tipo de objeto de Kubernetes
metadata:
  name: es-cliente-pod #Nombre del POD
  labels: #Etiquetas que permiten relacionar objetos
    app: es-cliente
    tier: backend
spec:
  containers:
    - image: jorgeheredia/microservices-lab:es-cliente-v1.0.0 #Ubicaci칩n del repositorio y la imagen a utilizar
      imagePullPolicy: Always
      name: es-cliente #Nombre del contenedor dentro del POD
      ports:
        - containerPort: 1005 #Puerto donde se acceder치 el servicio
    - image: mongo:4.0.14 #Se declara la ubicaci칩n del repositorio y la imagen a utilizar
      name: mongo-cliente
      ports:
        - name: mongo-cliente
          containerPort: 27017 #Puerto donde se acceder치 la base de datos
  imagePullSecrets:
    - name: dockerhubkey #Nombre del Secret creado para autenticarse a DockerHub
  restartPolicy: Always

