kubernetes:
  api:
    image:
      repository: jorgeheredia/microservices-lab
      tag: "es-curso"
      version: "-v1.0.0"
    replicaCount: 1
    service:
      type: NodePort
      port: 1004
    container:
      port: 1004
    ingress:
      host: es.curso
    nombre_global: es-curso
  db:
    image:
      repository: mongo
      tag: "4.0.14"
    service:
      type: NodePort
      port: 27017
    container:
      port: 27017
    nombre_global: db-curso
    database_name: cursosDB
    collection_name: Cursos

global:
  namespace: default
