apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-cliente-pod #Campo obligatorio para identificar el deployment
  namespace: default #namespace donde se instalara este deployment
  labels:
    tipomanager: Kubernetes
    version: "v1"
    service_model: entity
    tier: backend
    env: dev
    app: cliente
  annotations:
    desc: Unidad que nos permite gestionar de mejor manera los pods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: es-cliente  #nombre base que tendra el pod que tiene que coincidir con el templates.app
  template:
    metadata:
      labels:
        version: "v1"
        app: es-cliente
    spec:
      containers:
        - image: jorgeheredia/microservices-lab:es-cliente-v1.0.0 #Se declara la ubicacion del repositorio y la imagen a utilizar
          resources:
            requests:
              memory: 64Mi #El requerimiento de memoria para el pod
            limits:
              memory: 300Mi # El limite de memoria con la cual va trabajar
          imagePullPolicy: Always
          name: es-cliente #nombre base que tendra el contenedor dentro del pod
          ports:
            - containerPort: 1005
        - image: mongo:4.0.14 #Se declara la ubicacion del repositorio y la imagen a utilizar
          securityContext:
            runAsUser: 0
          resources:
            requests:
              memory: 100Mi #El requerimiento de memoria para el pod
            limits:
              memory: 600Mi # El limite de memoria con la cual va trabajar
          name: mongo
          ports:
            - name: mongo-cliente
              containerPort: 27017
      imagePullSecrets:
        - name: dockerhubkey
      restartPolicy: Always