apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.kubernetes.api.nombre_global }}
  name: {{ .Values.kubernetes.api.nombre_global }}-svc #nombre del servicio
spec:
  type: {{ .Values.kubernetes.api.service.type }} #tipo de servicio que va a desplegar
  ports:
    - name: "http"
      port: {{ .Values.kubernetes.api.service.port }} #puerto de conexion del pod
      targetPort: {{ .Values.kubernetes.api.container.port }}
  selector:
    app: {{ .Values.kubernetes.api.nombre_global }}-pod #el nombre del servicio al que se le hara conexion