apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.kubernetes.api.nombre_global }}
  name: {{ .Values.kubernetes.api.nombre_global }}-svc
spec:
  type: {{ .Values.kubernetes.api.service.type }}
  ports:
    - name: "api"
      port: {{ .Values.kubernetes.api.service.port }}
      targetPort: {{ .Values.kubernetes.api.container.port }}
    - name: "db"
      port: {{ .Values.kubernetes.db.service.port }}
      targetPort: {{ .Values.kubernetes.db.container.port }}
  selector:
    app: {{ .Values.kubernetes.api.nombre_global }}-pod