apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.kubernetes.api.nombre_global }}-ingress
spec:
  rules:
  - host: {{ .Values.kubernetes.api.ingress.host }}
    http:
      paths:
      - path: /es/cliente/v1
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kubernetes.api.nombre_global }}-svc
            port:
              number: {{ .Values.kubernetes.api.service.port }}