apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-cliente-pod #Campo obligatorio para identificar el deployment
  labels:
    version: "v1"
    service_model: entity
    tier: backend
    env: dev
    app: cliente
spec:
  replicas: 2
  selector:
    matchLabels:
      app: es-cliente  #nombre base que tendra el pod que tiene que coincidir con el templates.app
  template:
    metadata:
      labels:
        version: "v1"
        app: es-cliente
    spec:
      containers:
        - image: jorgeheredia/microservices-lab:es-cliente-v1.0.0 #Se declara la ubicacion del repositorio y la imagen a utilizar
          imagePullPolicy: Always
          name: es-cliente #nombre base que tendra el contenedor dentro del pod
          ports:
            - containerPort: 1005
          livenessProbe:
            httpGet:
              path: /health
              port: 1005
            initialDelaySeconds: 3
            periodSeconds: 3
        - image: mongo:4.0.14 #Se declara la ubicacion del repositorio y la imagen a utilizar
          name: mongo
          ports:
            - name: mongo-cliente
              containerPort: 27017
      imagePullSecrets:
        - name: dockerhubkey
      restartPolicy: Always