apiVersion: apps/v1
kind: Deployment #Tipo de objeto de Kubernetes
metadata:
  name: es-cliente-pod #Nombre del Deployment
  labels:
    app: cliente
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: es-cliente  #Define la relación del ReplicaSet con el POD que se debe monitorear
  template:
    metadata:
      labels:
        app: es-cliente #Nombre del POD
    spec:
      containers:
        - image: jorgeheredia/microservices-lab:es-cliente-v1.0.0 #Imagen del Servicio
          imagePullPolicy: Always
          name: es-cliente #Nombre del Contenedor del Servicio
          ports:
            - containerPort: 1005
        - image: mongo:4.0.14 #Imagen de MongoDB
          name: mongo #Nombre del Contenedor de MondoDB
          ports:
            - name: mongo-cliente
              containerPort: 27017
      imagePullSecrets:
        - name: dockerhubkey #Nombre del Secret creado para autenticarse a DockerHub
      restartPolicy: Always