apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: "{{ $value }}"
  {{- end }}
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "mongo{{ .Release.Namespace }}{{ .Values.name }}"
  resources:
    requests:
      storage: 1Gi