apiVersion: v1
kind: Service
metadata:
  labels:
    tipomanager: Kubernetes
  name: mongo #nombre del servicio
  annotations:
    desc:  Unidad que nos permite acceder a los pods atravez de la red
spec:
  type: LoadBalancer #tipo de servicio que va a desplegar
  ports:
    - name: "http"
      port: 27017 #puerto de conexion del pod
      targetPort: 27017
      nodePort: {{ .Values.portExt }}
  externalIPs: 
    - 192.168.15.2
  selector:
    app: mongo #el nombre del servicio al que se le hara conexion