apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  type: LoadBalancer #tipo de servicio que va a desplegar
  ports:
    - name: "http"
      port: 27017 #puerto de conexion del pod
      targetPort: 27017
  selector:
    role: mongo

