#Variables referentes a kubernetes
kubernetes:
  api:
  #imagen que sera utilizada en el despliegue
    image:
      repository: jorgeheredia/microservices-lab
      tag: "ms-reservarcupo"
      version: "-v1.0.0"
    #cantidad de replicas a utilizar
    replicaCount: 1
    service:
      type: NodePort
      port: 1002
    container:
      port: 1002
    ingress:
    #url desde la cual sera accedida el api
      host: ms.reservarcupo
    #nombre global del aplicativo
    nombre_global: ms-reservarcupo
    #Recursos que consume el deployment
  db:
    image:
      repository: mongo
      tag: "4.0.14"
    service:
      type: NodePort
      port: 27017
    container:
      port: 27017
    #nombre global del aplicativo
    nombre_global: db-reservarcupo
    #Recursos que consume el deployment
    database_name: cuposDB
    collection_name: Cupos

global:
  namespace: default
