#Variables referentes a kubernetes
kubernetes:
  api:
  #imagen que sera utilizada en el despliegue
    image:
      repository: jorgeheredia/microservices-lab
      tag: "ms-reservarcupo"
      version: "-v1.0.0"
    #cantidad de replicas a utilizar
    replicaCount: 1
    service:
      type: ClusterIP
      port: 1002
    container:
      port: 1002
    ingress:
    #url desde la cual sera accedida el api
      host: ms.reservarcupo
    #nombre global del aplicativo
    nombre_global: ms-reservarcupo
    #Recursos que consume el deployment
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "300Mi"
  db:
    image:
      repository: mongo
      tag: "4.0.14"
    service:
      type: LoadBalancer
      port: 27018
    container:
      port: 27017
    #nombre global del aplicativo
    nombre_global: db-reservarcupo
    #Recursos que consume el deployment
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "600Mi"
    database_name: cuposDB
    collection_name: Agenda


global:
  namespace: default
