kubernetes:
  api:
    image:
      repository: jorgeheredia/microservices-lab
      tag: "ms-reservarcupo"
      version: "-v1.0.0"
    replicaCount: 1
    service:
      type: NodePort
      port: 1002
    container:
      port: 1002
    ingress:
      host: ms.reservarcupo
    nombre_global: ms-reservarcupo
  db:
    image:
      repository: mongo
      tag: "4.0.14"
    service:
      type: NodePort
      port: 27017
    container:
      port: 27017
    nombre_global: db-reservarcupo
    database_name: cuposDB
    collection_name: Cupos

global:
  namespace: default
