apiVersion: v1
kind: Service #Tipo de objeto de Kubernetes
metadata:
  name: es-cliente-svc #Nombre del Servicio
  labels:
    name: es-cliente
spec:
  type: LoadBalancer #Tipo de servicio
  ports:
    - name: "http"
      port: 1005 #Puerto expuesto
      targetPort: 1005 #Puerto del servicio en el POD
  selector:
    app: es-cliente #Relación con el POD al cual se redirecciona el tráfico

