apiVersion: networking.k8s.io/v1
kind: Ingress #Tipo de objeto de Kubernetes
metadata:
  name: {{ .Values.kubernetes.api.nombre_global }}-ingress-rw #Nombre del Ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ms/consultarinscripciones/v1/consultar #Regla de direccionamiento
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.kubernetes.api.ingress.host }} #Nombre de dominio a resolver
    http:
      paths:
      - path: /es/inscripcion/v1/consultar
        pathType: Prefix
        backend:
          service:
            name: ms-consultarins-svc #Nombre del servicio al que se redireccionará la petición
            port:
              number: 1009
