apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kubernetes.api.nombre_global }}-pod
  labels:
    version: "v1"
    service_model: entity
    tier: backend
    env: dev
    app: {{ .Values.kubernetes.api.nombre_global }}
spec:
  replicas: {{ .Values.kubernetes.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kubernetes.api.nombre_global }}-pod
  template:
    metadata:
      labels:
        version: "v1"
        app: {{ .Values.kubernetes.api.nombre_global }}-pod
    spec:
      containers:
        - image: {{ .Values.kubernetes.api.image.repository }}:{{.Values.kubernetes.api.image.tag}}{{.Values.kubernetes.api.image.version }}
          name: {{ .Values.kubernetes.api.nombre_global }}
          ports:
            - containerPort: {{ .Values.kubernetes.api.container.port }}
          imagePullPolicy: Always
        - image: {{ .Values.kubernetes.db.image.repository }}:{{ .Values.kubernetes.db.image.tag }}
          name: mongo
          ports:
            - name: mongo
              containerPort: 27017
      imagePullSecrets:
        - name: dockerhubkey
      restartPolicy: Always