apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.kubernetes.api.nombre_global }}-ingress-rw #la interfaz de conexion con kubernetes
  namespace: {{.Values.global.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ms/consultarinscripciones/v1/consultar
spec:
  rules:
  - host: {{ .Values.kubernetes.api.ingress.host }} #dominio de conexion con kubernetes
    http:
      paths:
      - path: /es/inscripcion/v1
        backend:
          serviceName: ms-consultarins-svc #El servicio al que se hara conexion el ingress
          servicePort: 1009
