apiVersion: networking.k8s.io/v1
kind: Ingress #Tipo de objeto de Kubernetes
metadata:
  name: {{ .Values.kubernetes.api.nombre_global }}-ingress #Nombre del Ingress
spec:
  rules:
  - host: {{ .Values.kubernetes.api.ingress.host }} #Nombre de dominio a resolver
    http:
      paths:
        - path: /es/inscripcion/v1/crear
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.kubernetes.api.nombre_global }}-svc #Nombre del servicio al que se redireccionará la petición
              port:
                number: {{ .Values.kubernetes.api.service.port }}
        - path: /es/inscripcion/v1/aprobar
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.kubernetes.api.nombre_global }}-svc #Nombre del servicio al que se redireccionará la petición
              port:
                number: {{ .Values.kubernetes.api.service.port }}
        - path: /es/inscripcion/v1/rechazar
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.kubernetes.api.nombre_global }}-svc #Nombre del servicio al que se redireccionará la petición
              port:
                number: {{ .Values.kubernetes.api.service.port }}
        - path: /es/inscripcion/v1/actualizar
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.kubernetes.api.nombre_global }}-svc #Nombre del servicio al que se redireccionará la petición
              port:
                number: {{ .Values.kubernetes.api.service.port }}
